source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll", "~> 4.3.3"
gem "just-the-docs", "0.8.0"
gem "webrick", "~> 1.8"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap", "~> 1.4"
end

# Windows 平台需要
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# 性能优化
gem "jekyll-minifier", "~> 0.1.10"

# 本地开发
gem "jekyll-serve", "~> 0.1.0"